baseURL = "http://example.org/"
languageCode = "en-us"
title = "Aymen Furter | Solution Engineer"
[params]
  author = "Aymen Furter"
  github = "https://github.com/aymenfurter"
  linkedin = "https://www.linkedin.com/in/aymenfurter/"
  [params.pagination]
    articles = 5
[taxonomies]
  tag = "tags"
  category = "categories"
[permalinks]
  articles = "/articles/:slug/"
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
[menu]
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 3
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 4
  [[menu.main]]
    name = "Speeches"
    url = "#speeches"
    weight = 5
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true